config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :feeds, only: %i[index show]
  root 'feeds#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
# frozen_string_literal: true

class Feed < ApplicationRecord
  validates :url, :title, presence: true

  mount_uploader :image, ImageFeedUploader
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/feeds_controller.rb
# frozen_string_literal: true

class FeedsController < ApplicationController
  def index
    @feeds = FeedDecorator.decorate_collection(Feed.page(params[:page]))
  end

  def show
    @feed = get_feed
  end

  private

  def get_feed
    Feed.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/feeds/index.html.slim
.row.feeds
  - @feeds.each do |feed|
    - cache feed do
      .col-sm-4.col-xs-12
        a.feed(href="#{feed_path(feed)}")
          .img
            = image_tag feed.image.thumb.url
          .title = feed.title
          .short-content= feed.short_content


.text-center
  = paginate @feeds

app/views/feeds/show.html.slim
- cache @feed do
  .feed-page
    .title= @feed.title
    .img= image_tag @feed.image.url
    br
    .content= @feed.content.html_safe

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    title Idieutb
    = csrf_meta_tags
    = csp_meta_tag
    meta name="viewport" content="width=device-width, initial-scale=1"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      = render 'layouts/components/header'
      = yield
      = render 'layouts/components/footer'

app/views/layouts/components/_footer.html.slim
footer
  .footer-copyright.text-center
    = "© #{DateTime.current.year} Copyright: "
    a href="#{root_path}"
      = ENV['PAGE_NAME']

app/views/layouts/components/_header.html.slim
nav.navbar.navbar-inverse.navbar-static-top
  a.navbar-brand href="#{root_path}" 
    img.inline-block src="#{image_path('logo.gif')}"
    = "     #{ENV['PAGE_NAME']}"